// Mocks generated by Mockito 5.4.6 from annotations
// in wrestling_app/test/launch_url_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'launch_url_test.dart' as _i2;

/// A class which mocks [UrlLauncherWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlLauncherWrapper extends _i1.Mock
    implements _i2.UrlLauncherWrapper {
  MockUrlLauncherWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> canLaunch(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#canLaunch, [url]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> launch(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#launch, [url]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
